<?php

/**
 * This is the model base class for the table "video_gallery_video".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "VideoGalleryVideo".
 *
 * Columns in table "video_gallery_video" available as properties of the model,
 * followed by relations of table "video_gallery_video" available as properties of the model.
 *
 * @property integer $id
 * @property string $title
 * @property string $text
 * @property string $url
 * @property integer $gallery_id
 *
 * @property VideoGallery $gallery
 */
abstract class BaseVideoGalleryVideo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'video_gallery_video';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'VideoGalleryVideo|VideoGalleryVideos', $n);
	}

	public static function representingColumn() {
		return 'text';
	}

	public function rules() {
		$rules = array(
			array('title, gallery_id', 'required'),
			array('gallery_id', 'numerical', 'integerOnly'=>true),
			array('title, url,text', 'safe'),
			array('title, url', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, title, text, url, gallery_id', 'safe', 'on'=>'search'),
		);

        return array_merge($rules,parent::rules());
	}

	public function relations() {
		return array(
			'gallery' => array(self::BELONGS_TO, 'VideoGallery', 'gallery_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'title' => Yii::t('app', 'Title'),
			'text' => Yii::t('app', 'Text'),
			'url' => Yii::t('app', 'Url'),
			'gallery_id' => null,
			'gallery' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('title', $this->title, true);
		$criteria->compare('text', $this->text, true);
		$criteria->compare('url', $this->url, true);
		$criteria->compare('gallery_id', $this->gallery_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}